spring:
  application:
    name: nerochat

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      pool-name: SpringBootHikariCP

      data-source-properties:
        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  data:
    redis:
      host: ${REDIS_HOST}
      port: 19697
      password: ${REDIS_PASSWORD}
      connect-timeout: 5000ms
      timeout: 2000ms

  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET_BASE64}

email:
  verification:
    expiry-hours: 24
  password-reset:
    expiry-minutes: 15

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)